function EFFECT:Init( data )
	
	self.Position = data:GetOrigin()
    local owner = data:GetEntity()
    local angle = data:GetAngles()
    local normal = data:GetNormal()

	local emitter = ParticleEmitter( self.Position, true )
    local particle1 = emitter:Add( "effects/gstands_sethan", self.Position)
    local particle2 = emitter:Add( "decals/dark", self.Position)
    local particle3 = emitter:Add( "decals/dark", self.Position)
    local particle4 = emitter:Add( "decals/dark", self.Position)
    local particle5 = emitter:Add( "decals/dark", self.Position)
    local particle6 = emitter:Add( "decals/dark", self.Position)
    particle1:SetPos(self.Position)
    particle1:SetBounce(0)
    particle1:SetCollide(false)
    particle1:SetColor(255,255,255)
    particle1:SetDieTime(0.5)
    particle1:SetStartAlpha(255)
    particle1:SetEndAlpha(255)
    particle1:SetEndSize(50)
    particle1:SetStartSize(10)
    particle1:SetGravity(Vector(0,0,0))
    particle1:SetVelocity(Vector(normal.x * 500,normal.y * 500, 0))
    particle1:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))
    
    particle2:SetPos(self.Position)
    particle2:SetBounce(0)
    particle2:SetCollide(false)
    particle2:SetColor(255,255,255)
    particle2:SetDieTime(0.5)
    particle2:SetStartAlpha(255)
    particle2:SetEndAlpha(255)
    particle2:SetEndSize(50)
    particle2:SetStartSize(10)
    particle2:SetGravity(Vector(0,0,0))
    particle2:SetVelocity(Vector(normal.x * 500,normal.y * 500, 0))
    particle2:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))
    
    particle3:SetPos(self.Position)
    particle3:SetBounce(0)
    particle3:SetCollide(false)
    particle3:SetColor(255,255,255)
    particle3:SetDieTime(0.5)
    particle3:SetStartAlpha(255)
    particle3:SetEndAlpha(255)
    particle3:SetEndSize(50)
    particle3:SetStartSize(10)
    particle3:SetGravity(Vector(0,0,0))
    particle3:SetVelocity(Vector(normal.x * 400,normal.y * 400, 0))
    particle3:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))
    
    particle4:SetPos(self.Position)
    particle4:SetBounce(0)
    particle4:SetCollide(false)
    particle4:SetColor(255,255,255)
    particle4:SetDieTime(0.5)
    particle4:SetStartAlpha(255)
    particle4:SetEndAlpha(255)
    particle4:SetEndSize(50)
    particle4:SetStartSize(10)
    particle4:SetGravity(Vector(0,0,0))
    particle4:SetVelocity(Vector(normal.x * 300,normal.y * 300, 0))
    particle4:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))
    
    particle5:SetPos(self.Position)
    particle5:SetBounce(0)
    particle5:SetCollide(false)
    particle5:SetColor(255,255,255)
    particle5:SetDieTime(0.5)
    particle5:SetStartAlpha(255)
    particle5:SetEndAlpha(255)
    particle5:SetEndSize(50)
    particle5:SetStartSize(10)
    particle5:SetGravity(Vector(0,0,0))
    particle5:SetVelocity(Vector(normal.x * 200,normal.y * 200, 0))
    particle5:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))
    
    particle6:SetPos(self.Position)
    particle6:SetBounce(0)
    particle6:SetCollide(false)
    particle6:SetColor(255,255,255)
    particle6:SetDieTime(0.5)
    particle6:SetStartAlpha(255)
    particle6:SetEndAlpha(255)
    particle6:SetEndSize(50)
    particle6:SetStartSize(10)
    particle6:SetGravity(Vector(0,0,0))
    particle6:SetVelocity(Vector(normal.x * 100,normal.y * 100, 0))
    particle6:SetAngles(angle + Angle(0, normal:Angle().y + 90, 0))

	emitter:Finish()
end


function EFFECT:Think( )
	return false	
end

function EFFECT:Render()

end



